### PR TITLE
Fix "Undefined variable: url"

### PR DESCRIPTION
**Pull request by Robbilie**

### CODE REVIEW

**Comment by Robbilie** [comment]
I was looking through the repos code, looked interesting, tried it out, saw the issues and realized they were all (well 3 out of 5, dont know about #3 & #7) fixed already…

Noticed this little one in the logs and thought id PR it :)

**Comment by IngaFeick** [comment]
Thank you @Robbilie and @mre 👍

**Comment by Robbilie** [comment]
no worries @IngaFeick , would be cool if you could close the issues you already resolved ;)

**Comment by IngaFeick** [comment]
Good point Robert, I will look into it on the weekend. Thank you!

**Pull request merged**
